roles:
  AUTHENTICATION: authentication
  MESSAGING: messaging
  VERIFICATION: verification

entities:
  ORGANISATIONs: organistions
  USERs: users

cmds:
  CREATE: create
  DELETE: delete
  UPDATE: update
  GET_BY_ID: getById
  FIND_BY_EMAIL: findByEmail
  IS_CERTIFIED: isCertified
  REGISTER_VIA_EMAIL: registerViaEmail
  SEND_EMAIL: sendEmail

uris:
  amqp: 'amqp://0.0.0.0:5673'

http:
  authentication:
    registerViaEmail:
      port: 10100
      method: post

  verification:
    isCertified:
      port: 10101
      method: get

log:
  customlevels:
    ERROR: 1
    INFO: 1
    LOG: 1
    WARN: 1
    DEBUG: 0

emails:
  REGISTRATION_AUTHENTICATION: registrationAuthentication
