roles:
  AUTHENTICATION: authentication
  VERIFICATION: verification
cmds:
  IS_CERTIFIED: isCertified
  REGISTER_VIA_EMAIL: registerViaEmail
uris:
  amqp: 'amqp://0.0.0.0:5673'
log:
  customlevels:
    ERROR: 1
    INFO: 1
    LOG: 1
    WARN: 1
    DEBUG: 0
